apiVersion: "allocation.agones.dev/v1"
kind: GameServerAllocation
spec:
  required:
    # allocates 'Ready' GameServer with labels game: mc and edition: bedrock
    matchLabels:
      game: mc
      edition: bedrock
  scheduling: Packed
metadata:
  generateName: 'mc-bedrock-allocation-'
